# Generated by Django 3.2.6 on 2021-10-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_startime_events_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='endtime',
            field=models.DateTimeField(),
        ),
    ]
