# Generated by Django 3.2.6 on 2021-08-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_notes_updatedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='isStore',
            field=models.BooleanField(default=False),
        ),
    ]
